### ISSUE TITLE
`clj-time.core/equal?` not found

### ISSUE THREAD

**Issue by jimbru** [clj-time/clj-time#195] opened 2015-10-02 22:37 UTC
For unknown reasons, I'm unable to access the `equal?` function:
```
jimbru$ lein repl
INFO  | org.eclipse.jetty.util.log | Logging initialized @7264ms
nREPL server started on port 57434 on host 127.0.0.1 - nrepl://127.0.0.1:57434
REPL-y 0.3.7, nREPL 0.2.10
Clojure 1.6.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_60-b27
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

api.main=> (require '[clj-time.core :as t])
nil
api.main=> (def ld1 (t/local-date 2015 10 2))
#'api.main/ld1
api.main=> ld1
#<LocalDate 2015-10-02>
api.main=> (t/equal? ld1 ld1)

clojure.core/eval  core.clj: 2927
              ...
             java.lang.RuntimeException: No such var: t/equal?
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: No such var: t/equal?, compiling:(/private/var/folders/7g/6h9hkt3n35n_qzjqsq3ggd0cxwt162/T/form-init1304116952459760749.clj:1:1)
api.main=>
```

Running `[clj-time "0.11.0"]`.

**Comment by seancorfield** [comment] 2015-10-05 19:40
I am unable to reproduce this. In that same REPL session, what do you get for this:

    user=> (-> (ns-publics 'clj-time.core) keys sort)

(DateTimeProtocol InTimeUnitProtocol abuts? after? ago available-ids before? date-midnight date-time day day-of-week days days? default-time-zone deprecated do-at do-at* earliest end epoch equal? extend first-day-of-the-month first-day-of-the-month- floor from-now from-time-zone hour hours hours? in-days in-hours in-millis in-minutes in-months in-msecs in-seconds in-secs in-weeks in-years interval last-day-of-the-month last-day-of-the-month- latest local-date local-date-time local-time milli millis mins-ago minus minus- minute minutes minutes? month months months? now number-of-days-in-the-month overlap overlaps? plus plus- sec second seconds seconds? secs secs? start time-now time-zone-for-id time-zone-for-offset to-time-zone today today-at today-at-midnight utc week-number-of-year weeks weeks? within? year year-month years years? yesterday)

**Comment by jimbru** [comment] 2015-10-06 01:05
Hi @seancorfield, thanks for the response. Here's what I'm seeing:

```
jimbru$ lein repl
INFO  | org.eclipse.jetty.util.log | Logging initialized @8142ms
nREPL server started on port 49572 on host 127.0.0.1 - nrepl://127.0.0.1:49572
REPL-y 0.3.7, nREPL 0.2.10
Clojure 1.6.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_60-b27
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

api.main=> (require '[clj-time.core :as t])
nil
api.main=> (-> (ns-publics 'clj-time.core) keys sort)
(DateTimeProtocol
 abuts?
 after?
 ago
 before?
 date-midnight
 date-time
 day
 day-of-week
 days
 days?
 default-time-zone
 deprecated
 do-at
 do-at*
 earliest
 end
 epoch
 extend
 first-day-of-the-month
 from-now
 from-time-zone
 hour
 hours
 hours?
 in-days
 in-hours
 in-millis
 in-minutes
 in-months
 in-msecs
 in-seconds
 in-secs
 in-weeks
 in-years
 interval
 last-day-of-the-month
 latest
 local-date
 local-date-time
 milli
 millis
 mins-ago
 minus
 minus-
 minute
 minutes
 minutes?
 month
 months
 months?
 now
 number-of-days-in-the-month
 overlaps?
 plus
 plus-
 sec
 second
 seconds
 seconds?
 secs
 secs?
 start
 time-zone-for-id
 time-zone-for-offset
 to-time-zone
 today
 today-at
 today-at-midnight
 utc
 weeks
 weeks?
 within?
 year
 year-month
 years
 years?
 yesterday)
api.main=>
```

I didn't do a comparison, but just eyeballing it, it looks like a couple (including `equals?`) are missing. Not sure why :(

**Comment by seancorfield** [comment] 2015-10-06 03:03
`equal?` was added on May 12 so it would be in 0.10.0 and 0.11.0. I suspect one of your dependencies is pulling in an older version of clj-time. You should run `lein deps :tree` and see where the version conflicts are coming from.

Closing this since it's not a clj-time bug. Feel free to post in this ticket if you need more pointers in resolving your version conflicts.

**Closed by seancorfield** 2015-10-06 03:03 UTC
