### ISSUE TITLE
= does not return correct result across time zones

### ISSUE THREAD

**Issue by jasonab** [clj-time/clj-time#90] opened 2013-09-11 18:34 UTC
In the base Joda code, two DateTime objects are considered equal if they have the same basic millis value. This does not appear to carry over to clj-time:

(clj-time.coerce/to-long (time/date-time 2013 01 01 00)) = 1356998400000

(clj-time.coerce/to-long (time/from-time-zone (time/date-time 2013 01 01 01) (time/time-zone-for-offset 1))) = 1356998400000

(= (time/date-time 2013 01 01 00)
    (time/from-time-zone (time/date-time 2013 01 01 01) (time/time-zone-for-offset 1)))
is false, but should be true

**Comment by seancorfield** [comment] 2015-05-12 06:52
It does seem like these should compare equal if their coerced-to-long values compare equal.

**Comment by gws** [comment] 2015-05-12 19:39
I was curious about this too, but the [documentation](http://www.joda.org/joda-time/apidocs/org/joda/time/base/AbstractInstant.html#equals-java.lang.Object-) has a different definition of equality when `equals` is used, which is what [`clojure.core/=`](https://clojuredocs.org/clojure.core/=) is equivalent to:

>  Two objects which represent the same instant in time, but are in different time zones (based on time zone id), will be considered to be different. Only two objects with the same DateTimeZone, Chronology and instant are equal.

To get the kind of "value equality" you want, you'd need to call [`isEqual`](http://www.joda.org/joda-time/apidocs/org/joda/time/base/AbstractInstant.html#isEqual-org.joda.time.ReadableInstant-) explicitly:

> Is this instant equal to the instant passed in comparing solely by millisecond.

**Comment by seancorfield** [comment] 2015-05-12 19:55
So it sounds like this should be closed as "not a bug"?

**Comment by gws** [comment] 2015-05-12 20:12
Yes, but given that I had the same confusion I think equality could either be documented in the README around the `before?` and `after?` section, and/or we could add a similar `equal?` predicate to the protocol which is implemented with `isEqual`.

Since I'm talking about it I'm volunteering to do the work, but I'd like to hear maintainers' thoughts.

**Comment by seancorfield** [comment] 2015-05-12 20:14
Adding `equal?` sounds like a really good approach to me. @michaelklishin ?

**Comment by michaelklishin** [comment] 2015-05-12 20:17
@seancorfield agreed, let's add `equal?`.

**Comment by michaelklishin** [comment] 2015-05-12 21:08
Thank you, @gws!

**Closed** 2015-05-12 21:08 UTC

**Comment by gws** [comment] 2015-05-12 21:12
:+1: Glad to be able to contribute!
