### ISSUE TITLE
Is there a reason why `clj-time.local` uses DateTime instead of LocalDateTime?

### ISSUE THREAD

**Issue by dm3** [clj-time/clj-time#94] opened 2013-11-15 15:31 UTC
As I understand from the `joda-time` API, `LocalDateTime` is suited exactly for the task when a timezone is not wanted.

Why does the namespace which even hints at the usage of *local* dates doesn't use them at all? Is it an artifact of historical development?

**Comment by seancorfield** [comment] 2015-11-24 19:32
This seems a duplicate of #131 -- we're happy to entertain a PR for the documentation (or docstrings) that clarifies this.

**Closed by seancorfield** 2015-11-24 19:32 UTC
Labels: question
