### ISSUE TITLE
Ahead-of-time compiling a class that depends on clj-time.coerce produces error

### ISSUE THREAD

**Issue by bfabry** [clj-time/clj-time#172] opened 2015-03-18 18:44 UTC
Ahead-of-time compiling a class that depends on clj-time.coerce produces 
```
  java.lang.NoClassDefFoundError: clj_time/core/DateTimeProtocol
java.lang.ClassNotFoundException: clj_time.core.DateTimeProtocol
```

Is the correct answer just "don't do that"? Anyway I thought I'd document it here because I wasted a day figuring it out, so hopefully it saves someone else some time. A quick fix is to add clj-time.core to the aot list for your project.

Minimal reproducing project: https://github.com/bfabry/clj-time-aot-issue

**Comment by seancorfield** [comment] 2015-03-18 18:59
There are definitely problems around AOT compilation. Clojure 1.7.0 Alpha 5(?) threw this into stark relief by changing how AOT vs JIT code is handled and causing a slew of errors for folks in situations where earlier versions of Clojure had silently "done the wrong thing".

I'd be curious if adding `[clj-time.core]` to your `:require` in `test-aot.core` would also solve the problem?

**Comment by seancorfield** [comment] 2015-03-18 19:02
FWIW, if I clone your repo and try `lein repl` or `lein compile` or `lein test`, I do not see the problem you mention -- could you explain how to actually repro that error?

**Comment by bfabry** [comment] 2015-03-18 19:24
I did try adding clj-time.core to the require list, didn't help.

On my machine that repo consistently fails when running lein clean && lein repl =/ leiningen 2.5.1, java 1.7.0_71, just tried and same on java 1.8.0_40

I've also rm'd my .m2 directory and reinstalled leiningen a couple of times. I'm not really sure where to go from here, and I have a "fix" that works for me so probably won't flounder any further. If you have anything you'd like me to try I'd be happy to though.

**Comment by seancorfield** [comment] 2015-03-18 19:29
Hmm, not sure what to say. Here's what I see:
```
(! 508)-> lein clean && lein repl
Compiling test-aot.core
nREPL server started on port 51768 on host 127.0.0.1 - nrepl://127.0.0.1:51768
REPL-y 0.3.5, nREPL 0.2.6
Clojure 1.6.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_31-b13
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

test-aot.core=> Bye for now!

Wed Mar 18 12:28:23
(sean)-(jobs:0)-(/Developer/workspace/clj-time-aot-issue)
(! 509)-> git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean

Wed Mar 18 12:28:25
(sean)-(jobs:0)-(/Developer/workspace/clj-time-aot-issue)
(! 510)-> lein version
Leiningen 2.5.1 on Java 1.8.0_31 Java HotSpot(TM) 64-Bit Server VM
```

**Comment by bfabry** [comment] 2015-03-18 20:28
Yeah, neither =/
```
-- INSERT -- ➤ lein clean && lein repl                                                                                                                       
Compiling test-aot.core
Exception in thread "main" java.lang.NoClassDefFoundError: clj_time/core/DateTimeProtocol, compiling:(/private/var/folders/gz/1n0l436s20xd20fzsr5lt9nh0000gn/T/form-init6209218998669664736.clj:1:124)
	at clojure.lang.Compiler.load(Compiler.java:7142)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NoClassDefFoundError: clj_time/core/DateTimeProtocol
	at clj_time.coerce__init.load(Unknown Source)
	at clj_time.coerce__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.loadClassForName(RT.java:2093)
	at clojure.lang.RT.load(RT.java:430)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at test_aot.core$loading__4958__auto__.invoke(core.clj:1)
	at test_aot.core__init.load(Unknown Source)
	at test_aot.core__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.loadClassForName(RT.java:2093)
	at clojure.lang.RT.load(RT.java:430)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at user$eval5.invoke(form-init6209218998669664736.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.eval(Compiler.java:6692)
	at clojure.lang.Compiler.eval(Compiler.java:6692)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	... 11 more
Caused by: java.lang.ClassNotFoundException: clj_time.core.DateTimeProtocol
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 57 more
Exception in thread "Thread-3" clojure.lang.ExceptionInfo: Subprocess failed {:exit-code 1}
	at clojure.core$ex_info.invoke(core.clj:4403)
	at leiningen.core.eval$fn__6725.invoke(eval.clj:236)
	at clojure.lang.MultiFn.invoke(MultiFn.java:231)
	at leiningen.core.eval$eval_in_project.invoke(eval.clj:337)
	at leiningen.repl$server$fn__10717.invoke(repl.clj:241)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:624)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1862)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invoke(core.clj:628)
	at clojure.core$bound_fn_STAR_$fn__4140.doInvoke(core.clj:1884)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:745)
REPL server launch timed out.

bfabry@5141-bfabry:~/Code/test-aot
-- INSERT -- ➤ git status                                                                                                                                    
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

**Comment by icambron** [comment] 2015-03-19 03:10
FWIW--and it's not much--I'm suddenly having a similar problem:

```
-> lein clean && lein with-profile main uberjar
Compiling prod-start
java.lang.RuntimeException: No such var: coerce/to-sql-time, compiling:(zensight/db.clj:84:5)
```

A couple notes:

 1. The version of clj-time doesn't seem to matter. Same with lein. In fact, I've been AOTing clj-time (and even the exact code that's requiring it) for a while but now suddenly it's breaking. It must be triggered by some other, seemingly unrelated change to my codebase or its dependencies. In fact, I wonder if the error here is merely a symptom of some deeper, more sinister problem.

 2. I pulled @bfabry's repo and, aggravatingly, it works OK for me. So perhaps my issue is subtlety different, or it's some sort of heisenbug.

**Comment by seancorfield** [comment] 2015-03-31 21:37
@icambron Looks like you tracked your problem down to Storm packaging old dependencies? @bfabry any update from you? If not, I think we should close this issue as "unable to reproduce / works for me" at this point.

**Comment by icambron** [comment] 2015-03-31 21:45
@seancorfield Yeah, sorry, should have updated the ticket here too.

**Closed** 2015-03-31 21:53 UTC

**Comment by bfabry** [comment] 2015-03-31 21:59
@seancorfield no updates really, just periodically "still happens" and is fixed by adding clj-time.core to my aot list. Happy for it to be closed as I can't figure any steps to reliably reproduce, just wanted it documented somewhere how to 'fix' for anyone else who comes across it, closed issue works fine for that :-)

**Comment by jconti** [comment] 2016-10-18 15:07
Not a comforting resolution.  I too have had this issue.  I will remove the explicit :aot of the library and see if it still reproduces for me.

**Comment by BWStearns** [comment] 2018-08-03 20:48
Just started encountering this. Has anyone found root cause?

**Comment by seancorfield** [comment] 2018-08-03 23:29
@BWStearns As noted above, this isn't a clj-time issue per se -- it's almost certainly caused by one of your existing dependencies.

**Comment by seancorfield** [comment] 2018-08-03 23:30
(also, if you're on Java 8 or later, consider using Java Time directly -- or a wrapper such as clojure/java-time per clj-time's README)
