### ISSUE TITLE
clj-time.core/floor doesn't preserve timezone

### ISSUE THREAD

**Issue by laczoka** [clj-time/clj-time#208] opened 2016-04-14 15:11 UTC
Check:
(require '[clj-time.core :refer :all])
(floor (from-time-zone (now) (time-zone-for-id "Europe/London")) day)

**Comment by seancorfield** [comment] 2016-10-11 21:52
Closing as a duplicate of #204 (for which we're awaiting an updated PR).

**Closed by seancorfield** 2016-10-11 21:52 UTC
