### ISSUE TITLE
Unable to resolve symbol: utc  clj_time/format.clj:44

### ISSUE THREAD

**Issue by orzyx** [clj-time/clj-time#214] opened 2016-07-07 09:05 UTC
I found this exception in my app. I use clj_time (version 0.12) in storm which use clojure 1.7

**Comment by michaelklishin** [comment] 2016-07-07 09:07
This seems legit: the time zone is supposed to be passed as a string or constant there?

**Comment by orzyx** [comment] 2016-07-07 09:10
My code:
(t/to-time-zone (c/from-long timestamp) (t/time-zone-for-offset +8))

**Comment by michaelklishin** [comment] 2016-07-07 09:18
Can you post full stack trace, please?

**Comment by orzyx** [comment] 2016-07-07 09:23
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve symbol: utc in this context, compiling:(clj_time/format.clj:44:6)
	at clojure.lang.Compiler.analyze(Compiler.java:6543) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler.analyze(Compiler.java:6485) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3791) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6725) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler.analyze(Compiler.java:6524) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler.analyze(Compiler.java:6485) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5861) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5296) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3925) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6721) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler.analyze(Compiler.java:6524) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6711) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler.analyze(Compiler.java:6524) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler.access$300(Compiler.java:38) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:577) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6723) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler.analyze(Compiler.java:6524) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler.analyze(Compiler.java:6485) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler.eval(Compiler.java:6786) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler.load(Compiler.java:7227) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RT.loadResourceScript(RT.java:371) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RT.loadResourceScript(RT.java:362) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RT.load(RT.java:446) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RT.load(RT.java:412) ~[clojure-1.7.0.jar:?]
	at clojure.core$load$fn__5448.invoke(core.clj:5866) ~[clojure-1.7.0.jar:?]
	at clojure.core$load.doInvoke(core.clj:5865) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.7.0.jar:?]
	at clojure.core$load_one.invoke(core.clj:5671) ~[clojure-1.7.0.jar:?]
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711) ~[clojure-1.7.0.jar:?]
	at clojure.core$load_lib.doInvoke(core.clj:5710) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:142) ~[clojure-1.7.0.jar:?]
	at clojure.core$apply.invoke(core.clj:632) ~[clojure-1.7.0.jar:?]
	at clojure.core$load_libs.doInvoke(core.clj:5749) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) ~[clojure-1.7.0.jar:?]
	at clojure.core$apply.invoke(core.clj:632) ~[clojure-1.7.0.jar:?]
	at clojure.core$require.doInvoke(core.clj:5832) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:421) ~[clojure-1.7.0.jar:?]
	at clj_time.coerce$eval6262$loading__5340__auto____6263.invoke(coerce.clj:1) ~[?:?]
	at clj_time.coerce$eval6262.invoke(coerce.clj:1) ~[?:?]
	at clojure.lang.Compiler.eval(Compiler.java:6782) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler.eval(Compiler.java:6771) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler.load(Compiler.java:7227) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RT.loadResourceScript(RT.java:371) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RT.loadResourceScript(RT.java:362) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RT.load(RT.java:446) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RT.load(RT.java:412) ~[clojure-1.7.0.jar:?]
	at clojure.core$load$fn__5448.invoke(core.clj:5866) ~[clojure-1.7.0.jar:?]
	at clojure.core$load.doInvoke(core.clj:5865) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.7.0.jar:?]
	at clojure.core$load_one.invoke(core.clj:5671) ~[clojure-1.7.0.jar:?]
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711) ~[clojure-1.7.0.jar:?]
	at clojure.core$load_lib.doInvoke(core.clj:5710) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:142) ~[clojure-1.7.0.jar:?]
	at clojure.core$apply.invoke(core.clj:632) ~[clojure-1.7.0.jar:?]
	at clojure.core$load_libs.doInvoke(core.clj:5749) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) ~[clojure-1.7.0.jar:?]
	at clojure.core$apply.invoke(core.clj:632) ~[clojure-1.7.0.jar:?]
	at clojure.core$require.doInvoke(core.clj:5832) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:457) ~[clojure-1.7.0.jar:?]
	at com.gf.cheetah.risk.rules.exchange.trading_calendar$eval6021$loading__5340__auto____6022.invoke(trading_calendar.clj:1) ~[?:?]
	at com.gf.cheetah.risk.rules.exchange.trading_calendar$eval6021.invoke(trading_calendar.clj:1) ~[?:?]
	at clojure.lang.Compiler.eval(Compiler.java:6782) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler.eval(Compiler.java:6771) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler.load(Compiler.java:7227) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RT.loadResourceScript(RT.java:371) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RT.loadResourceScript(RT.java:362) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RT.load(RT.java:446) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RT.load(RT.java:412) ~[clojure-1.7.0.jar:?]
	at clojure.core$load$fn__5448.invoke(core.clj:5866) ~[clojure-1.7.0.jar:?]
	at clojure.core$load.doInvoke(core.clj:5865) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.7.0.jar:?]
	at clojure.core$load_one.invoke(core.clj:5671) ~[clojure-1.7.0.jar:?]
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711) ~[clojure-1.7.0.jar:?]
	at clojure.core$load_lib.doInvoke(core.clj:5710) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:142) ~[clojure-1.7.0.jar:?]
	at clojure.core$apply.invoke(core.clj:632) ~[clojure-1.7.0.jar:?]
	at clojure.core$load_libs.doInvoke(core.clj:5749) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) ~[clojure-1.7.0.jar:?]
	at clojure.core$apply.invoke(core.clj:632) ~[clojure-1.7.0.jar:?]
	at clojure.core$require.doInvoke(core.clj:5832) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Var.invoke(Var.java:379) ~[clojure-1.7.0.jar:?]
	at clara.rules.RuleLoader.loadRules(RuleLoader.java:41) ~[cheetah-risk-storm-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.gf.cheetah.risk.model.binary.AndRules.initialize(AndRules.java:23) ~[cheetah-risk-storm-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.gf.cheetah.risk.rules.ExchangeRule.initialize(ExchangeRule.java:17) ~[cheetah-risk-storm-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.gf.cheetah.risk.rules.ExchangeRule.initialize(ExchangeRule.java:9) ~[cheetah-risk-storm-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.gf.cheetah.risk.storm.bolt.BaseRiskBlt.initRules(BaseRiskBlt.java:94) ~[cheetah-risk-storm-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.gf.cheetah.risk.storm.bolt.exchange.TradeTimeBlt.prepare(TradeTimeBlt.java:66) ~[cheetah-risk-storm-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.storm.daemon.executor$fn__8226$fn__8239.invoke(executor.clj:795) ~[storm-core-1.0.0.jar:1.0.0]
	at org.apache.storm.util$async_loop$fn__554.invoke(util.clj:482) [storm-core-1.0.0.jar:1.0.0]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
Caused by: java.lang.RuntimeException: Unable to resolve symbol: utc in this context
	at clojure.lang.Util.runtimeException(Util.java:221) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler.resolveIn(Compiler.java:7019) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler.resolve(Compiler.java:6963) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6924) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Compiler.analyze(Compiler.java:6506) ~[clojure-1.7.0.jar:?]
	... 91 more
23086 [Thread-17-rule-engine-bolt-executor[3 3]] ERROR o.a.s.util - Halting process: ("Worker died")
java.lang.RuntimeException: ("Worker died")
	at org.apache.storm.util$exit_process_BANG_.doInvoke(util.clj:341) [storm-core-1.0.0.jar:1.0.0]
	at clojure.lang.RestFn.invoke(RestFn.java:423) [clojure-1.7.0.jar:?]
	at org.apache.storm.daemon.worker$fn__8827$fn__8828.invoke(worker.clj:758) [storm-core-1.0.0.jar:1.0.0]
	at org.apache.storm.daemon.executor$mk_executor_data$fn__8046$fn__8047.invoke(executor.clj:271) [storm-core-1.0.0.jar:1.0.0]
	at org.apache.storm.util$async_loop$fn__554.invoke(util.clj:494) [storm-core-1.0.0.jar:1.0.0]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]

**Comment by seancorfield** [comment] 2016-10-11 21:50
I have been unable to reproduce this in any way and cannot see how it would possibly occur: the clj-time.coerce namespace requires in all of clj-time.core and that's where utc is defined.

@orzyx If you can provide a small self-contined example project that reproduces this, feel free to link to it here and we'll take a look. Absent that, I'm closing this.

**Closed by seancorfield** 2016-10-11 21:50 UTC
